"""Tool #22: Add PR Comment - Adds response comments to GitHub PR."""

from typing import Dict, Any
from src.integrations.client_factory import get_github_client
from src.config import settings
from src.utils.logging import get_logger
import time

logger = get_logger(__name__)


class AddPRCommentTool:
    """Tool for adding response comments to GitHub PR."""
    
    def __init__(self):
        self.name = "add_pr_comment"
        self.description = "Adds response comments to GitHub pull request"
    
    async def execute(self, repository_info: Dict[str, Any], 
                     pr_number: int,
                     comment_body: str,
                     comment_type: str = "general") -> Dict[str, Any]:
        """
        Add a comment to the GitHub PR.
        
        Args:
            repository_info: Repository information (owner, repo)
            pr_number: Pull request number
            comment_body: Comment text to add
            comment_type: Type of comment (general, update, response)
            
        Returns:
            Dict containing comment creation results
        """
        start_time = time.time()
        
        try:
            owner = repository_info["owner"]
            repo = repository_info["repo"]
            
            logger.info("Adding PR comment", 
                       owner=owner, repo=repo, pr_number=pr_number, type=comment_type)
            
            # Format comment based on type
            formatted_comment = self._format_comment(comment_body, comment_type)
            
            # Add comment to PR
            success = await get_github_client().add_pull_request_comment(owner, repo, pr_number, formatted_comment)
            
            duration_ms = int((time.time() - start_time) * 1000)
            
            if success:
                logger.info("PR comment added successfully", 
                           pr_number=pr_number,
                           comment_type=comment_type,
                           duration_ms=duration_ms)
                
                return {
                    "success": True,
                    "pr_number": pr_number,
                    "comment_added": True,
                    "comment_type": comment_type,
                    "repository": repository_info,
                    "duration_ms": duration_ms
                }
            else:
                return {
                    "success": False,
                    "error": "Failed to add comment to PR",
                    "duration_ms": duration_ms
                }
            
        except Exception as e:
            duration_ms = int((time.time() - start_time) * 1000)
            logger.error("Error adding PR comment", 
                        error=str(e), duration_ms=duration_ms)
            
            return {
                "success": False,
                "error": str(e),
                "duration_ms": duration_ms
            }
    
    def _format_comment(self, comment_body: str, comment_type: str) -> str:
        """Format comment based on type."""
        
        if comment_type == "update":
            return f"""## 🤖 AI-SDLC Automation Update

{comment_body}

---
*This comment was automatically generated by the AI-SDLC Automation System*"""
        
        elif comment_type == "response":
            return f"""## 🔄 Response to Feedback

{comment_body}

---
*This response was automatically generated by the AI-SDLC Automation System*"""
        
        elif comment_type == "completion":
            return f"""## ✅ Implementation Complete

{comment_body}

---
*This update was automatically generated by the AI-SDLC Automation System*"""
        
        else:  # general
            return f"""{comment_body}

---
*This comment was automatically generated by the AI-SDLC Automation System*"""


# Global tool instance
add_pr_comment_tool = AddPRCommentTool()
